"""E3 adversarial falsification study: delayed temporal causality.

Preregistered in:
research/audits/current/2026-09-embodiment-self-boundary-falsification-v1.md

The current AgencyModel receives contemporaneous activation/delta pairs. This
study tests whether genuine delayed consequences are lost while an immediate
external distractor is incorrectly promoted.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
import random
from typing import Sequence

from symbiont.core.agency import AgencyModel

# Component-level falsification specimen marker (see §62 of
# docs/design/herencia-evolutiva-multidimensional.md). This module
# freshly constructs isolated AgencyModel/InferredBodySchema specimens
# purely to falsify the algorithm itself. It never imports or
# constructs a live Symbiont/Individual, never attaches a specimen to
# one, and never crosses synthetic state back into cognition. Checked
# structurally and at runtime by
# tests/experimental_integrity/test_embodiment_inheritance_integrity.py.
__falsification_specimen__ = True

_STUDY_ID = "embodiment.temporal-causality-challenge"
AGENCY_THRESHOLD = 0.5


@dataclass(frozen=True, slots=True)
class TemporalSeedResult:
    seed: int
    delay0_confidence: float
    delay1_confidence: float
    delay3_confidence: float
    variable_delay_confidence: float
    immediate_external_confidence: float

    def as_dict(self) -> dict[str, object]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class TemporalCausalityStudy:
    seeds: tuple[int, ...]
    steps: int
    per_seed: tuple[TemporalSeedResult, ...]
    delay0_detection_rate: float
    delay1_detection_rate: float
    delay3_detection_rate: float
    variable_delay_detection_rate: float
    immediate_external_false_positive_rate: float
    replay_deterministic: bool
    h1_supported: bool

    def as_dict(self) -> dict[str, object]:
        return {
            "study_id": _STUDY_ID,
            "seeds": list(self.seeds),
            "steps": self.steps,
            "per_seed": [item.as_dict() for item in self.per_seed],
            "delay0_detection_rate": self.delay0_detection_rate,
            "delay1_detection_rate": self.delay1_detection_rate,
            "delay3_detection_rate": self.delay3_detection_rate,
            "variable_delay_detection_rate": self.variable_delay_detection_rate,
            "immediate_external_false_positive_rate": self.immediate_external_false_positive_rate,
            "replay_deterministic": self.replay_deterministic,
            "h1_supported": self.h1_supported,
        }


def _normalize_seeds(seeds: Sequence[int]) -> tuple[int, ...]:
    if isinstance(seeds, (str, bytes)) or not isinstance(seeds, Sequence):
        raise ValueError("seeds must be a sequence of unique integers")
    result = tuple(seeds)
    if not result or len(result) > 64 or len(set(result)) != len(result):
        raise ValueError("seeds must contain between 1 and 64 unique entries")
    if any(isinstance(seed, bool) or not isinstance(seed, int) for seed in result):
        raise ValueError("seeds must contain integers only")
    return result


def _confidence(model: AgencyModel) -> float:
    return float(model.agency_confidence.get("out.0", 0.0))


def _run_seed(seed: int, *, steps: int) -> TemporalSeedResult:
    rng = random.Random(seed)
    activations = [
        0.0 if rng.random() < 0.30 else rng.uniform(0.25, 1.0)
        for _ in range(steps + 8)
    ]
    variable_delays = [rng.randint(1, 4) for _ in range(steps + 8)]

    models = {
        "delay0": AgencyModel(),
        "delay1": AgencyModel(),
        "delay3": AgencyModel(),
        "variable": AgencyModel(),
        "external": AgencyModel(),
    }

    for tick in range(steps):
        act = activations[tick]
        noise = lambda: rng.gauss(0.0, 0.015)

        d0 = 0.38 * act + noise()
        d1 = 0.38 * (activations[tick - 1] if tick >= 1 else 0.0) + noise()
        d3 = 0.38 * (activations[tick - 3] if tick >= 3 else 0.0) + noise()
        vd = variable_delays[tick]
        dv = 0.38 * (activations[tick - vd] if tick >= vd else 0.0) + noise()

        # External immediate distractor: yoked to the current activation but
        # not generated by the bodily effector.
        ext = 0.38 * act + noise()

        current = {"out.0": act}
        models["delay0"].record_step(current, {"in.0": d0})
        models["delay1"].record_step(current, {"in.0": d1})
        models["delay3"].record_step(current, {"in.0": d3})
        models["variable"].record_step(current, {"in.0": dv})
        models["external"].record_step(current, {"in.0": ext})

    return TemporalSeedResult(
        seed=seed,
        delay0_confidence=_confidence(models["delay0"]),
        delay1_confidence=_confidence(models["delay1"]),
        delay3_confidence=_confidence(models["delay3"]),
        variable_delay_confidence=_confidence(models["variable"]),
        immediate_external_confidence=_confidence(models["external"]),
    )


def run_temporal_causality_challenge_study(
    *,
    seeds: Sequence[int] = (101, 127, 149, 173, 211, 257, 307, 353, 401, 457),
    steps: int = 600,
) -> TemporalCausalityStudy:
    normalized = _normalize_seeds(seeds)
    if steps < 50 or steps > 100_000:
        raise ValueError("steps must be within [50, 100000]")

    results = tuple(_run_seed(seed, steps=steps) for seed in normalized)
    replay = tuple(_run_seed(seed, steps=steps) for seed in normalized)
    n = len(results)

    rate = lambda attr: sum(getattr(item, attr) >= AGENCY_THRESHOLD for item in results) / n
    d0 = rate("delay0_confidence")
    d1 = rate("delay1_confidence")
    d3 = rate("delay3_confidence")
    dv = rate("variable_delay_confidence")
    ext = rate("immediate_external_confidence")
    deterministic = results == replay

    # Strong H1 requires delayed causal sensitivity and rejection of the
    # immediate external distractor. This is intentionally demanding.
    supported = (
        d0 >= 0.70
        and d1 >= 0.70
        and d3 >= 0.70
        and dv >= 0.70
        and ext <= 0.10
        and deterministic
    )

    return TemporalCausalityStudy(
        seeds=normalized,
        steps=steps,
        per_seed=results,
        delay0_detection_rate=d0,
        delay1_detection_rate=d1,
        delay3_detection_rate=d3,
        variable_delay_detection_rate=dv,
        immediate_external_false_positive_rate=ext,
        replay_deterministic=deterministic,
        h1_supported=supported,
    )


__all__ = [
    "TemporalSeedResult",
    "TemporalCausalityStudy",
    "run_temporal_causality_challenge_study",
]
