"""Agency Acquisition Bridge (Agency Acquisition v1 §6.1, §19-§25, §84).

One reusable component owns the acquisition loop from a concrete
ActionAttempt to learned ActionDimensions, for both the full OrganismRuntime
(through ActionDomain) and the reduced Symbiont:

    ActionAttempt -> InterventionSignature -> observed Effect -> CausalEvidence
      -> contingency / counterfactual comparison -> Controllability -> Agency
      -> ActionDimension -> BodySchema evidence

No step requires a MotorCompetence.  Competence-level estimates are added on
top when (and only when) the executing commitment names a competence.
Only real physical transitions and passive windows enter the ledger; nothing
generated by imagination can reach this component's write methods.
"""

from __future__ import annotations

import hashlib
from collections import deque
from dataclasses import dataclass
from typing import TYPE_CHECKING, Mapping

from ..provenance import CausalEvent, CausalRef, ProvenanceLog
from .action import MotorCommand
from .attempt import ActionAttempt, attempt_id_for_command
from .commitment import ActionCommitment
from .dimension import (
    ActionDimension,
    ActionDimensionDiscoveryPolicy,
    ActionDimensionRegistry,
    DimensionEvidence,
    assess_family,
    opaque_dimension_id,
)
from .effects import EffectAtom, EffectMatcher, EffectSpace, atoms_from_changes, bounded_atoms
from .evidence import (
    CausalEvidence,
    CausalEvidenceLedger,
    CounterfactualFreeView,
    OpportunityView,
    PredictionError,
    SensorimotorTransition,
)
from .footprint import (
    FootprintRegistry,
    atom_estimates,
    footprint_effect_id,
    pulses_from,
    version_ref,
)
from .intervention import (
    InterventionSignature,
    InterventionSignatureRegistry,
    opaque_channel_ref,
)
from .model import (
    AgencyEstimate,
    AgencyModel,
    CausalSourceKind,
    CompetenceEffectModel,
    ControllabilityEstimate,
    ControllabilityModel,
)

if TYPE_CHECKING:
    from ..core.embodiment.body_schema import BodySchemaEngine

_RECENT_ATTEMPTS = 64
_PATTERN_CACHE = 1024


@dataclass(frozen=True, slots=True)
class CausalUpdate:
    """What one real transition changed in organism-owned causal knowledge."""

    evidence: CausalEvidence
    signature_controllability: ControllabilityEstimate | None
    signature_agency: AgencyEstimate | None
    dimension: ActionDimension | None
    dimension_evidence: DimensionEvidence | None
    dimension_controllability: ControllabilityEstimate | None
    dimension_agency: AgencyEstimate | None
    competence_controllability: ControllabilityEstimate | None
    competence_agency: AgencyEstimate | None


@dataclass(frozen=True, slots=True)
class CompetenceGrounding:
    """Causal grounding that lets a recurrent controller become a competence (§28)."""

    temporal_signature: InterventionSignature
    step_signature_refs: tuple[str, ...]
    dimension_id: str
    effect_id: str
    controllability: ControllabilityEstimate
    agency: AgencyEstimate
    evidence_refs: tuple[str, ...]


_ATOM_CATALOG = 8192
_GROUNDING_EVIDENCE = 64


class AgencyAcquisition:
    """Shared owner of attempts, signatures, causal evidence and learned dimensions."""

    SCHEMA_VERSION = 3
    FOOTPRINT_COMMITMENTS_PER_SOURCE = 256

    def __init__(
        self,
        *,
        dimension_policy: ActionDimensionDiscoveryPolicy | None = None,
        use_counterfactual_evidence: bool = True,
        use_agency_model: bool = True,
        footprint_effects: bool = False,
    ) -> None:
        self.dimension_policy = dimension_policy or ActionDimensionDiscoveryPolicy()
        # Ablation switches exist for E1 only; the organism default is full.
        self.use_counterfactual_evidence = bool(use_counterfactual_evidence)
        self.use_agency_model = bool(use_agency_model)
        # Factorized Effect Representation v1 §14: competences are grounded on
        # causal footprints (entity-keyed) instead of whole-state effects.
        self.footprint_effects = bool(footprint_effects)
        self._atom_catalog: dict[str, EffectAtom] = {}
        self.signatures = InterventionSignatureRegistry()
        self.effect_space = EffectSpace()
        self.causal_evidence = CausalEvidenceLedger()
        self.effect_model = CompetenceEffectModel()
        self.controllability_model = ControllabilityModel()
        self.agency_model = AgencyModel()
        self.action_dimensions = ActionDimensionRegistry(policy=self.dimension_policy)
        self.effect_matcher = EffectMatcher()
        self.pending_attempt: ActionAttempt | None = None
        self.last_attempt: ActionAttempt | None = None
        self.recent_attempts: deque[ActionAttempt] = deque(maxlen=_RECENT_ATTEMPTS)
        self.attempt_count = 0
        # (migrated, unresolved) evidence items at the last pre-atom restore.
        self.atom_migration: tuple[int, int] | None = None
        # Organism-level causal provenance (Causal Provenance v1), shared by
        # every domain; footprints are its first adopter.
        self.provenance = ProvenanceLog()
        self.footprints = FootprintRegistry(provenance=self.provenance)
        self._footprint_commitments: dict[tuple[str, ...], deque[str]] = {}
        self._open_commitment: tuple[str, tuple[str, ...]] | None = None
        self._surface_ids: tuple[str, ...] | None = None
        self._surface_fingerprint: str | None = None
        self._pattern_signatures: dict[
            tuple[str, tuple[tuple[tuple[str, float], ...], ...]],
            tuple[InterventionSignature, tuple[InterventionSignature, ...]],
        ] = {}

    # -- surface --------------------------------------------------------------
    def bind_surface(
        self,
        actuator_ids: tuple[str, ...] | None,
        *,
        surface_fingerprint: str | None,
    ) -> None:
        """Current executability of known dimensions; knowledge is never erased."""
        self._surface_ids = actuator_ids
        self._surface_fingerprint = surface_fingerprint
        self.action_dimensions.bind_surface(
            None
            if actuator_ids is None
            else tuple(opaque_channel_ref(actuator_id) for actuator_id in actuator_ids),
            surface_fingerprint=surface_fingerprint,
        )

    # -- attempts (T11 open / T1 close) ----------------------------------------
    def open_attempt(
        self,
        *,
        command: MotorCommand,
        commitment: ActionCommitment,
        context_ref: str,
        actuation_ref: str,
        tick: int,
    ) -> ActionAttempt:
        if self.pending_attempt is not None:
            raise RuntimeError("previous ActionAttempt must be closed before a new command")
        if command.commitment_id != commitment.commitment_id:
            raise RuntimeError("attempt command is not owned by the commitment")
        signature = self.signatures.signature_for_command(
            command=command,
            controller_id=commitment.controller_id,
            tick=tick,
        )
        attempt = ActionAttempt(
            attempt_id=attempt_id_for_command(command.command_id),
            commitment_id=commitment.commitment_id,
            controller_id=commitment.controller_id,
            competence_id=commitment.competence_id,
            intervention_signature_id=signature.signature_id,
            context_ref=context_ref,
            embodiment_id=command.embodiment_id,
            surface_fingerprint=command.surface_fingerprint,
            motor_command_ref=command.command_id,
            actuation_ref=actuation_ref,
            started_tick=tick,
        )
        self.pending_attempt = attempt
        self.attempt_count += 1
        return attempt

    def close_attempt(
        self,
        *,
        tick: int,
        state_before_ref: str,
        state_after_ref: str,
        prediction_ref: str | None,
        observed_effect_id: str | None,
        prediction_error: PredictionError | None,
        observed_changes: Mapping[str, float] | None = None,
    ) -> SensorimotorTransition:
        """Close the pending attempt on the first later observation.

        ``observed_changes`` (opaque feature -> change) yields the
        transition's atoms (Factorized Effect Representation v1 §5).
        """
        attempt = self.pending_attempt
        if attempt is None:
            raise RuntimeError("no open ActionAttempt to close")
        closed = attempt.close(tick=tick)
        self.pending_attempt = None
        self.last_attempt = closed
        self.recent_attempts.append(closed)
        digest = hashlib.sha256(f"transition:{closed.attempt_id}".encode("utf-8")).hexdigest()[:24]
        return SensorimotorTransition(
            transition_id=f"transition.{digest}",
            tick_start=closed.started_tick,
            tick_end=tick,
            context_ref=closed.context_ref,
            commitment_id=closed.commitment_id,
            controller_id=closed.controller_id,
            competence_id=closed.competence_id,
            attempt_id=closed.attempt_id,
            intervention_signature_id=closed.intervention_signature_id,
            state_before_ref=state_before_ref,
            motor_command_ref=closed.motor_command_ref,
            actuation_ref=closed.actuation_ref,
            prediction_ref=prediction_ref,
            state_after_ref=state_after_ref,
            observed_effect_id=observed_effect_id,
            prediction_error=prediction_error,
            observed_effect_atoms=self._atom_ids(observed_changes or {}),
        )

    def _atom_ids(self, changes: Mapping[str, float]) -> tuple[str, ...]:
        """Atoms of one transition; the catalog remembers each atom's feature."""
        atoms = atoms_from_changes(changes)
        for atom in atoms:
            if atom.effect_id not in self._atom_catalog and len(self._atom_catalog) < _ATOM_CATALOG:
                self._atom_catalog[atom.effect_id] = atom
        return tuple(sorted({atom.effect_id for atom in atoms}))

    def _effect_atom_ids(self, effect_id: str) -> tuple[str, ...] | None:
        effect = self.effect_space.get(effect_id)
        if effect is None:
            return None
        return tuple(
            sorted({atom.effect_id for atom in bounded_atoms(effect.transition_signature)})
        )

    def discard_pending_attempt(self) -> None:
        """An open attempt belongs to the old embodiment (§80); never credit it."""
        self.pending_attempt = None

    # -- T2 causal learning ------------------------------------------------------
    def _attempt_surface(self, transition: SensorimotorTransition) -> str:
        last = self.last_attempt
        if last is None or last.attempt_id != transition.attempt_id:
            raise RuntimeError("causal learning must follow the attempt it closes")
        return last.surface_fingerprint

    def _signature_expectation(self, signature_id: str) -> str | None:
        effects = {
            effect: count
            for effect, count in self.causal_evidence.signature_effects(signature_id).items()
            if effect is not None
        }
        if not effects:
            return None
        return min(effects.items(), key=lambda item: (-item[1], item[0]))[0]

    def _counterfactual_view(self) -> OpportunityView:
        if self.use_counterfactual_evidence:
            return self.causal_evidence
        # E1 ablation: estimates see only the source's own windows.
        return CounterfactualFreeView(self.causal_evidence)

    def _refresh_source(
        self,
        ledger: OpportunityView,
        *,
        source_kind: CausalSourceKind,
        source_ref: str,
        current: tuple[str, str | None] | None,
        tick: int,
        dimension_signature_refs: tuple[str, ...] | None = None,
    ) -> None:
        """Re-estimate every other known consequence of a source that just acted.

        Acting changes the source's opportunity count for *all* effects: the
        consequences that did not occur this time must lose reliability too,
        otherwise stale control/agency would survive a changed body (§115).
        """
        for estimate in self.controllability_model.for_source(source_kind, source_ref):
            if (estimate.effect_id, estimate.context_id) == current:
                continue
            self.controllability_model.update_from_ledger(
                ledger,
                source_kind=source_kind,
                source_ref=source_ref,
                effect_id=estimate.effect_id,
                context_id=estimate.context_id,
                tick=tick,
                dimension_signature_refs=dimension_signature_refs,
            )
        if not self.use_agency_model:
            return
        for agency in self.agency_model.for_source(source_kind, source_ref):
            if (agency.effect_id, agency.context_id) == current:
                continue
            self.agency_model.update_from_ledger(
                ledger,
                source_kind=source_kind,
                source_ref=source_ref,
                effect_id=agency.effect_id,
                context_id=agency.context_id,
                tick=tick,
                prediction_match=agency.prediction_match,
                dimension_signature_refs=dimension_signature_refs,
            )

    def learn(
        self,
        transition: SensorimotorTransition,
        *,
        body_schema: "BodySchemaEngine | None",
        competence_prediction_match: float | None = None,
    ) -> CausalUpdate:
        signature_id = transition.intervention_signature_id
        assert signature_id is not None  # guaranteed by SensorimotorTransition
        effect_id = transition.observed_effect_id
        tick = transition.tick_end
        expected = self._signature_expectation(signature_id)
        evidence = self.causal_evidence.observe(transition)
        self._track_pulse(transition, tick=tick)
        self.effect_model.observe(evidence)
        ledger = self._counterfactual_view()

        s_ctrl = s_agency = None
        if effect_id is not None:
            s_ctrl = self.controllability_model.update_from_ledger(
                ledger,
                source_kind=CausalSourceKind.INTERVENTION,
                source_ref=signature_id,
                effect_id=effect_id,
                context_id=None,
                tick=tick,
            )
            if self.use_agency_model:
                s_agency = self.agency_model.update_from_ledger(
                    ledger,
                    source_kind=CausalSourceKind.INTERVENTION,
                    source_ref=signature_id,
                    effect_id=effect_id,
                    context_id=None,
                    tick=tick,
                    prediction_match=(
                        None
                        if expected is None
                        else self.effect_matcher.match(
                            self.effect_space,
                            expected_effect_id=expected,
                            observed_effect_id=effect_id,
                        )
                    ),
                )

        self._refresh_source(
            ledger,
            source_kind=CausalSourceKind.INTERVENTION,
            source_ref=signature_id,
            current=(effect_id, None) if effect_id is not None else None,
            tick=tick,
        )

        dimension = dimension_evidence = d_ctrl = d_agency = None
        signature = self.signatures.get(signature_id)
        if signature is not None and signature.temporal_pattern_ref is None:
            dimension, dimension_evidence = self.action_dimensions.evaluate_family(
                channel_refs=signature.channel_refs,
                signature_refs=self.signatures.family(signature.channel_refs),
                ledger=ledger,
                surface_fingerprint=self._attempt_surface(transition),
            )
            dominant = dimension_evidence.dominant_effect_id
            if dimension is not None and dominant is not None:
                d_ctrl = self.controllability_model.update_from_ledger(
                    ledger,
                    source_kind=CausalSourceKind.DIMENSION,
                    source_ref=dimension.dimension_id,
                    effect_id=dominant,
                    context_id=None,
                    tick=tick,
                    dimension_signature_refs=dimension.intervention_signature_refs,
                )
                if self.use_agency_model:
                    d_agency = self.agency_model.update_from_ledger(
                        ledger,
                        source_kind=CausalSourceKind.DIMENSION,
                        source_ref=dimension.dimension_id,
                        effect_id=dominant,
                        context_id=None,
                        tick=tick,
                        prediction_match=(
                            None
                            if effect_id is None
                            else self.effect_matcher.match(
                                self.effect_space,
                                expected_effect_id=dominant,
                                observed_effect_id=effect_id,
                            )
                        ),
                        dimension_signature_refs=dimension.intervention_signature_refs,
                    )
                self._refresh_source(
                    ledger,
                    source_kind=CausalSourceKind.DIMENSION,
                    source_ref=dimension.dimension_id,
                    current=(dominant, None),
                    tick=tick,
                    dimension_signature_refs=dimension.intervention_signature_refs,
                )
                dimension = self.action_dimensions.record_controllability(
                    dimension.dimension_id, d_ctrl.confidence
                )

        c_ctrl = c_agency = None
        if transition.competence_id is not None and effect_id is not None:
            c_ctrl = self.controllability_model.update_from_ledger(
                ledger,
                source_kind=CausalSourceKind.COMPETENCE,
                source_ref=transition.competence_id,
                effect_id=effect_id,
                context_id=transition.context_ref,
                tick=tick,
            )
            if self.use_agency_model:
                c_agency = self.agency_model.update_from_ledger(
                    ledger,
                    source_kind=CausalSourceKind.COMPETENCE,
                    source_ref=transition.competence_id,
                    effect_id=effect_id,
                    context_id=transition.context_ref,
                    tick=tick,
                    prediction_match=competence_prediction_match,
                )

        if transition.competence_id is not None:
            self._refresh_source(
                ledger,
                source_kind=CausalSourceKind.COMPETENCE,
                source_ref=transition.competence_id,
                current=(effect_id, transition.context_ref) if effect_id is not None else None,
                tick=tick,
            )

        if body_schema is not None and effect_id is not None:
            self._observe_body(
                body_schema,
                effect_id=effect_id,
                tick=tick,
                sources=(
                    (signature_id, s_ctrl, s_agency),
                    (transition.competence_id, c_ctrl, c_agency),
                ),
            )
        return CausalUpdate(
            evidence=evidence,
            signature_controllability=s_ctrl,
            signature_agency=s_agency,
            dimension=dimension,
            dimension_evidence=dimension_evidence,
            dimension_controllability=d_ctrl,
            dimension_agency=d_agency,
            competence_controllability=c_ctrl,
            competence_agency=c_agency,
        )

    def _observe_body(
        self,
        body_schema: "BodySchemaEngine",
        *,
        effect_id: str,
        tick: int,
        sources: tuple[
            tuple[str | None, ControllabilityEstimate | None, AgencyEstimate | None], ...
        ],
    ) -> None:
        effect = self.effect_space.get(effect_id)
        if effect is None:
            return
        for source_ref, control, agency in sources:
            if source_ref is None or control is None:
                continue
            body_schema.observe_agentic_sensorimotor_evidence(
                causal_source_ref=source_ref,
                effect_id=effect_id,
                feature_refs=effect.feature_refs,
                controllability_confidence=control.confidence,
                agency_confidence=agency.confidence if agency is not None else 0.0,
                tick=tick,
            )

    def observe_passive_window(
        self,
        *,
        tick_start: int,
        tick_end: int,
        context_ref: str | None,
        prior_state_ref: str,
        resulting_state_ref: str,
        changes: Mapping[str, float],
    ) -> CausalEvidence:
        """Counterfactual evidence: bodily change while nothing was commanded."""
        effect = self.effect_space.observe(changes)
        return self.causal_evidence.observe_passive_window(
            tick_start=tick_start,
            tick_end=tick_end,
            context_ref=context_ref,
            prior_state_ref=prior_state_ref,
            resulting_state_ref=resulting_state_ref,
            effect_id=effect.effect_id if effect is not None else None,
            effect_atoms=self._atom_ids(changes),
        )

    # -- footprints (Factorized Effect Representation v1 §4.2, §13.7) -----------
    def _track_pulse(self, transition: SensorimotorTransition, *, tick: int) -> None:
        """A new commitment closes the previous pulse: refresh that source."""
        signature = self.signatures.get(str(transition.intervention_signature_id))
        if signature is None:
            return
        source = tuple(sorted(signature.channel_refs))
        opened = self._open_commitment
        if opened is not None and opened[0] != transition.commitment_id:
            self.refresh_footprint(opened[1], tick=tick)
        commitments = self._footprint_commitments.setdefault(
            source, deque(maxlen=self.FOOTPRINT_COMMITMENTS_PER_SOURCE)
        )
        if not commitments or commitments[-1] != transition.commitment_id:
            commitments.append(transition.commitment_id)
        self._open_commitment = (transition.commitment_id, source)

    def _channels_of(self, signature_id: str) -> tuple[str, ...] | None:
        signature = self.signatures.get(signature_id)
        return tuple(sorted(signature.channel_refs)) if signature is not None else None

    def refresh_footprint(self, source: tuple[str, ...], *, tick: int) -> None:
        """Re-estimate one source's footprint from its retained pulses.

        E1 ablations see no footprint: a footprint is a causal claim that
        needs both the counterfactual baseline and the agency model.
        """
        if not (self.use_counterfactual_evidence and self.use_agency_model):
            return
        source = tuple(sorted(source))
        commitments = self._footprint_commitments.get(source)
        if not commitments:
            return
        evidence: list[CausalEvidence] = []
        retained: list[str] = []
        for commitment_id in commitments:
            items = self.causal_evidence.commitment_evidence(commitment_id)
            if items:
                retained.append(commitment_id)
                evidence.extend(items)
        commitments.clear()
        commitments.extend(retained)
        pulses = [
            pulse for pulse in pulses_from(evidence, self._channels_of) if pulse.source == source
        ]
        estimates = atom_estimates(pulses, self.causal_evidence.passive_evidence, tick=tick)
        self.footprints.update({source: estimates.get(source, {})}, tick=tick)
        if self.footprint_effects:
            self._register_footprint_effect(source)

    def _register_footprint_effect(self, source: tuple[str, ...]) -> None:
        """Keep the entity's effect current; a vanished footprint keeps its last one."""
        members = self.footprints.member_estimates(source)
        atoms = tuple(self._atom_catalog[a] for a in sorted(members) if a in self._atom_catalog)
        if atoms:
            self.effect_space.register_footprint(
                footprint_effect_id(source),
                atoms,
                support=max(estimate.pulses for estimate in members.values()),
            )

    def _ground_on_footprints(
        self,
        *,
        controller_seed_ref: str,
        temporal: InterventionSignature,
        steps: tuple[InterventionSignature, ...],
        tick: int,
    ) -> "CompetenceGrounding | None":
        """Ground a controller on causal footprints (Factorized Effects §14.1).

        The competence's effect entity is its own channel set.  Until that set
        has a footprint of its own (its own pulses), the prediction is the
        union of the per-channel footprints of the channels it drives — a
        provisional grounding that avoids the Gap A loop; its own executions
        then confirm or revise it.
        """
        source = tuple(sorted({channel for step in steps for channel in step.channel_refs}))
        if not source:
            return None
        if self.footprints.footprint_of(source) is not None:
            parts, provisional = [source], False
        else:
            parts = [(c,) for c in source if self.footprints.footprint_of((c,)) is not None]
            provisional = True
        estimates = {
            atom: estimate
            for part in parts
            for atom, estimate in self.footprints.member_estimates(part).items()
        }
        atoms = tuple(self._atom_catalog[a] for a in sorted(estimates) if a in self._atom_catalog)
        if not atoms:
            return None
        effect_id = footprint_effect_id(source)
        values = list(estimates.values())
        support = min(estimate.pulses for estimate in values)
        self.effect_space.register_footprint(effect_id, atoms, support=support)
        dimension_id = opaque_dimension_id(source)
        last_tick = max(estimate.estimated_tick for estimate in values)
        hit_rate = sum(e.hits / e.pulses for e in values) / len(values)
        expected = sum(e.expected_quiet_rate for e in values) / len(values)
        contrast = sum(e.contrast for e in values) / len(values)
        passive = max(e.passive_windows for e in values)
        control = ControllabilityEstimate(
            source_kind=CausalSourceKind.DIMENSION,
            source_ref=dimension_id,
            effect_id=effect_id,
            context_id=None,
            confidence=max(0.0, min(1.0, sum(e.controllability for e in values) / len(values))),
            reliability=hit_rate,
            counterfactual_rate=expected,
            causal_advantage=contrast,
            action_support=support,
            counterfactual_support=passive,
            last_updated_tick=last_tick,
        )
        agency = AgencyEstimate(
            source_kind=CausalSourceKind.DIMENSION,
            source_ref=dimension_id,
            effect_id=effect_id,
            context_id=None,
            confidence=max(0.0, min(1.0, sum(e.agency for e in values) / len(values))),
            temporal_contingency=hit_rate,
            causal_specificity=max(0.0, min(1.0, contrast)),
            prediction_match=None,
            support=support,
            counterfactual_support=passive,
            last_updated_tick=last_tick,
        )
        evidence_refs = tuple(
            dict.fromkeys(
                item.evidence_id
                for estimate in values
                for commitment_id in estimate.pulse_commitments
                for item in self.causal_evidence.commitment_evidence(commitment_id)
            )
        )[-_GROUNDING_EVIDENCE:]
        if not evidence_refs:
            return None
        versions = [
            version_ref(
                self.footprints.version_of(part).entity_id, self.footprints.version_of(part).version
            )
            for part in parts
        ]
        competence = CausalRef("competence", controller_seed_ref)
        self.provenance.emit(
            CausalEvent(
                tick=int(tick),
                domain="competence",
                operation="ground",
                subject=competence,
                caused_by=tuple(versions),
                produced=(competence,),
                rule="footprint_union" if provisional else "own_footprint",
                parameters={
                    "effect_id": effect_id,
                    "provisional": provisional,
                    "atoms": len(atoms),
                    "channels": len(source),
                    "covered_channels": len(parts) if provisional else len(source),
                },
            )
        )
        return CompetenceGrounding(
            temporal_signature=temporal,
            step_signature_refs=tuple(step.signature_id for step in steps),
            dimension_id=dimension_id,
            effect_id=effect_id,
            controllability=control,
            agency=agency,
            evidence_refs=evidence_refs,
        )

    # -- derived views --------------------------------------------------------
    def self_caused_features(self, *, min_confidence: float) -> set[str]:
        """Effect features the organism probably causes, from any causal source."""
        features: set[str] = set()
        for estimate in self.agency_model.estimates:
            if estimate.confidence < min_confidence:
                continue
            effect = self.effect_space.get(estimate.effect_id)
            if effect is not None:
                features.update(
                    feature for feature in effect.feature_refs if not feature.startswith("channel.")
                )
        return features

    def agentic_dimension_ids(self) -> tuple[str, ...]:
        threshold = self.dimension_policy.agentic_confidence
        agentic = {
            estimate.source_ref
            for estimate in self.agency_model.estimates_for(CausalSourceKind.DIMENSION)
            if estimate.confidence >= threshold
        }
        return tuple(sorted(item for item in agentic if self.action_dimensions.get(item)))

    def causal_information_gain(self, channel_refs: tuple[str, ...]) -> float:
        """How much trying this opaque channel set could clarify causality (§24-§25).

        Not a reward: it only ranks exploratory opportunities.  High when the
        family is barely tried, when its recurring effect lacks counterfactual
        contrast, when passive (no-intervention) windows are missing, or when
        intensity variants of the family were never tried.
        """
        family = self.signatures.family(channel_refs)
        support = sum(self.causal_evidence.signature_support(ref) for ref in family)
        untried = 1.0 / (1.0 + support)
        evidence = (
            assess_family(self.causal_evidence, family, self.dimension_policy) if family else None
        )
        if evidence is None or evidence.dominant_effect_id is None:
            unresolved = 1.0 if support else 0.0
        else:
            contrast = min(1.0, evidence.counterfactual_support / 8.0)
            advantage = max(0.0, evidence.causal_advantage or 0.0)
            unresolved = max(0.0, 1.0 - contrast * min(1.0, advantage * 4.0))
        passive_missing = 1.0 / (1.0 + len(self.causal_evidence.passive_evidence))
        intensity_missing = (
            1.0 - max(self.signatures.intensity_coverage(ref) for ref in family) if family else 1.0
        )
        compared = sum(
            1
            for ref in self.signatures.neighbours(channel_refs)
            if self.causal_evidence.signature_support(ref) > 0
        )
        comparison_missing = 1.0 / (1.0 + compared)
        return max(
            0.0,
            min(
                1.0,
                max(
                    untried,
                    0.4 * unresolved
                    + 0.2 * passive_missing
                    + 0.2 * intensity_missing
                    + 0.2 * comparison_missing,
                ),
            ),
        )

    def record_commitment_pattern(
        self,
        *,
        commitment_id: str,
        controller_seed_ref: str,
        tick: int,
    ) -> InterventionSignature | None:
        """Temporal family of a completed commitment/controller episode (§77-§79).

        Names the ordered sequence of commands actually issued under the
        commitment, so recurrent controller sequences become countable
        intervention families without being treated as skills.
        """
        command_refs = tuple(
            item.action_ref
            for item in sorted(
                self.causal_evidence.commitment_evidence(commitment_id),
                key=lambda evidence: evidence.observation_tick,
            )
            if item.action_ref is not None
            and self.signatures.signature_of_command(item.action_ref) is not None
        )
        if not command_refs:
            return None
        return self.signatures.signature_for_sequence(
            command_refs=command_refs,
            controller_seed_ref=controller_seed_ref,
            tick=tick,
        )

    # -- competence convergence (Wave 4) -------------------------------------
    def ground_competence(
        self,
        *,
        controller_seed_ref: str,
        patterns: tuple[Mapping[str, float], ...],
        tick: int = -1,
    ) -> CompetenceGrounding | None:
        """Converge a recurrent motor pattern with the causal ledger (§28, §122).

        A controller may become a MotorCompetence only when at least one of its
        steps lies on a learned, currently available ActionDimension whose
        dominant EffectSpace effect is controllable and agentic.  The
        competence's effect is that EffectSpace effect; nothing here consults
        the controller's own private statistics.
        """
        driven = tuple(pattern for pattern in patterns if pattern)
        if not driven:
            return None
        key = (controller_seed_ref, tuple(tuple(sorted(item.items())) for item in driven))
        cached = self._pattern_signatures.get(key)
        if cached is None:
            # Pure identities of an immutable controller seed; memoized.
            cached = self.signatures.signature_for_pattern_sequence(
                driven, controller_seed_ref=controller_seed_ref
            )
            self._pattern_signatures[key] = cached
            while len(self._pattern_signatures) > _PATTERN_CACHE:
                self._pattern_signatures.pop(next(iter(self._pattern_signatures)))
        temporal, steps = cached
        if self.footprint_effects:
            return self._ground_on_footprints(
                controller_seed_ref=controller_seed_ref, temporal=temporal, steps=steps, tick=tick
            )
        threshold = self.dimension_policy.agentic_confidence
        best: tuple[float, float, str, str] | None = None
        for step in steps:
            dimension = self.action_dimensions.get(opaque_dimension_id(step.channel_refs))
            if dimension is None or not dimension.embodiment_bound:
                continue
            for agency in self.agency_model.for_source(
                CausalSourceKind.DIMENSION, dimension.dimension_id
            ):
                if agency.confidence < threshold or self.effect_space.get(agency.effect_id) is None:
                    continue
                control = self.controllability_model.estimate(
                    source_kind=CausalSourceKind.DIMENSION,
                    source_ref=dimension.dimension_id,
                    effect_id=agency.effect_id,
                )
                if control is None or control.confidence <= 0.0:
                    continue
                candidate = (
                    agency.confidence,
                    control.confidence,
                    dimension.dimension_id,
                    agency.effect_id,
                )
                if (
                    best is None
                    or candidate[:2] > best[:2]
                    or (candidate[:2] == best[:2] and candidate[2:] < best[2:])
                ):
                    best = candidate
        if best is None:
            return None
        _agency_value, _control_value, dimension_id, effect_id = best
        dimension = self.action_dimensions.get(dimension_id)
        assert dimension is not None
        control = self.controllability_model.estimate(
            source_kind=CausalSourceKind.DIMENSION, source_ref=dimension_id, effect_id=effect_id
        )
        agency = self.agency_model.estimate(
            source_kind=CausalSourceKind.DIMENSION, source_ref=dimension_id, effect_id=effect_id
        )
        assert control is not None and agency is not None
        evidence_refs = self.causal_evidence.signature_evidence_ids(
            dimension.intervention_signature_refs, effect_id=effect_id
        )
        if not evidence_refs:
            return None
        return CompetenceGrounding(
            temporal_signature=temporal,
            step_signature_refs=tuple(step.signature_id for step in steps),
            dimension_id=dimension_id,
            effect_id=effect_id,
            controllability=control,
            agency=agency,
            evidence_refs=evidence_refs,
        )

    # -- persistence -------------------------------------------------------
    def checkpoint(self) -> dict[str, object]:
        """Bounded abstract causal state; open attempts and raw baselines are not kept."""
        return {
            "schema_version": self.SCHEMA_VERSION,
            "attempt_count": self.attempt_count,
            "intervention_signatures": self.signatures.checkpoint(),
            "action_dimensions": self.action_dimensions.checkpoint(),
            # Active causal statistics (§82.2): the estimates are path-dependent
            # (each refreshes when its own source acts), so they are persisted
            # rather than re-derived from final ledger counts.
            "controllability": self.controllability_model.checkpoint(),
            "agency": self.agency_model.checkpoint(),
            "footprint_effects": self.footprint_effects,
            "atom_catalog": [
                [atom_id, atom.feature_ref, atom.direction, atom.magnitude_class]
                for atom_id, atom in sorted(self._atom_catalog.items())
            ],
            "provenance": self.provenance.checkpoint(),
            "footprints": self.footprints.checkpoint(),
            "footprint_commitments": [
                {"source": list(source), "commitments": list(commitments)}
                for source, commitments in sorted(self._footprint_commitments.items())
            ],
            "open_commitment": (
                {"commitment": self._open_commitment[0], "source": list(self._open_commitment[1])}
                if self._open_commitment is not None
                else None
            ),
        }

    def restore_causal_state(
        self,
        *,
        effect_space: Mapping[str, object] | None,
        causal_evidence: Mapping[str, object] | None,
        acquisition: Mapping[str, object] | None,
        body_schema: "BodySchemaEngine | None",
    ) -> None:
        if effect_space is not None:
            self.effect_space = EffectSpace.restore(dict(effect_space))
        if causal_evidence is not None:
            self.causal_evidence = CausalEvidenceLedger.restore(dict(causal_evidence))
            if causal_evidence.get("schema_version") != CausalEvidenceLedger.SCHEMA_VERSION:
                # Factorized Effects §8: pre-atom evidence gets the exact atoms of
                # its whole-state effect while that effect is still known.
                self.atom_migration = self.causal_evidence.migrate_atoms(self._effect_atom_ids)
        persisted_estimates = False
        if acquisition is not None:
            version = acquisition.get("schema_version")
            if version not in (1, 2, self.SCHEMA_VERSION):
                raise ValueError("unsupported agency acquisition checkpoint")
            raw_count = acquisition.get("attempt_count", 0)
            if not isinstance(raw_count, int) or raw_count < 0:
                raise ValueError("invalid attempt count")
            self.attempt_count = raw_count
            raw_signatures = acquisition.get("intervention_signatures")
            raw_dimensions = acquisition.get("action_dimensions")
            self.signatures = InterventionSignatureRegistry.restore(
                raw_signatures if isinstance(raw_signatures, Mapping) else None
            )
            self.action_dimensions = ActionDimensionRegistry.restore(
                raw_dimensions if isinstance(raw_dimensions, Mapping) else None,
                policy=self.dimension_policy,
            )
            # Schema 3: causal provenance frontier and footprints (none before).
            if "footprint_effects" in acquisition:
                self.footprint_effects = bool(acquisition["footprint_effects"])
            self._atom_catalog = {}
            for atom_id, feature, direction, magnitude in acquisition.get("atom_catalog", []):
                atom = EffectAtom(str(feature), int(direction), int(magnitude))
                if atom.effect_id != atom_id:
                    raise ValueError("atom catalog entry does not match its identity")
                self._atom_catalog[atom_id] = atom
            self.provenance = ProvenanceLog.restore(acquisition.get("provenance"))
            self.footprints = FootprintRegistry.restore(
                acquisition.get("footprints"), provenance=self.provenance
            )
            self._footprint_commitments = {
                tuple(str(v) for v in raw["source"]): deque(
                    (str(c) for c in raw["commitments"]),
                    maxlen=self.FOOTPRINT_COMMITMENTS_PER_SOURCE,
                )
                for raw in acquisition.get("footprint_commitments", [])
            }
            raw_open = acquisition.get("open_commitment")
            self._open_commitment = (
                (str(raw_open["commitment"]), tuple(str(v) for v in raw_open["source"]))
                if isinstance(raw_open, Mapping)
                else None
            )
            if version in (2, self.SCHEMA_VERSION):
                self.controllability_model = ControllabilityModel()
                self.controllability_model.restore_estimates(acquisition.get("controllability"))
                self.agency_model = AgencyModel()
                self.agency_model.restore_estimates(acquisition.get("agency"))
                persisted_estimates = True
        else:
            # Historical checkpoints (Sensorimotor v3) never learned dimensions:
            # start empty rather than regenerating them from the surface (§83).
            self.signatures = InterventionSignatureRegistry()
            self.action_dimensions = ActionDimensionRegistry(policy=self.dimension_policy)
        self.pending_attempt = None
        self.bind_surface(self._surface_ids, surface_fingerprint=self._surface_fingerprint)
        self.effect_model.rebuild(self.causal_evidence)
        if not persisted_estimates:
            # Migration only: older checkpoints lacked the estimate tables.
            self.rebuild_views(body_schema=body_schema)

    def rebuild_views(self, *, body_schema: "BodySchemaEngine | None") -> None:
        members = self.action_dimensions.members
        self.effect_model.rebuild(self.causal_evidence)
        view = self._counterfactual_view()
        self.controllability_model.rebuild(self.causal_evidence, dimensions=members, view=view)
        self.agency_model.rebuild(self.causal_evidence, dimensions=members, view=view)
        if body_schema is None:
            return
        body_schema.reset_sensorimotor_view()
        for item in self.causal_evidence.intervention_evidence:
            if item.effect_id is None:
                continue
            sources = []
            for kind, ref, context in (
                (CausalSourceKind.INTERVENTION, item.intervention_signature_id, None),
                (CausalSourceKind.COMPETENCE, item.competence_id, item.context_ref),
            ):
                if ref is None:
                    continue
                sources.append(
                    (
                        ref,
                        self.controllability_model.estimate(
                            source_kind=kind,
                            source_ref=ref,
                            effect_id=item.effect_id,
                            context_id=context,
                        ),
                        self.agency_model.estimate(
                            source_kind=kind,
                            source_ref=ref,
                            effect_id=item.effect_id,
                            context_id=context,
                        ),
                    )
                )
            self._observe_body(
                body_schema,
                effect_id=item.effect_id,
                tick=item.observation_tick,
                sources=tuple(sources),
            )


__all__ = ["AgencyAcquisition", "CausalUpdate", "CompetenceGrounding"]
